package com.test.exceptionTest;

public class Test5 {

	public static void main(String[] args) {
		
		
		
	}
	
	public static void f(){
		
		throw new MyException("我自己定义的异常....");
		
	}
}
